spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb?TimeZone=Asia/Kolkata
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

cloud:
  aws:
    credentials:
      access-key: abcd
      secret-key: efgh
    region:
      static: ap-southeast-2
    sns:
      topic:
        order-events-arn: arn:aws:sns:ap-southeast-2:211888003693:order-events
    sqs:
      dlq-url: https://sqs.ap-southeast-2.amazonaws.com/211888003693/order-update-dlq
      order-updates-queue-url: https://sqs.ap-southeast-2.amazonaws.com/211888003693/order-updates-queue