spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb?TimeZone=Asia/Kolkata
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

cloud:
    region:
      static: ap-southeast-2
    sns:
      topic:
        order-events-arn: arn:aws:sns:ap-southeast-2:211888003693:order-events